# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

httptest2::with_mock_dir("api/path/apis/list_apis", {
  test_that("list_apis() returns expected result", {
    test_result <- list_apis()
    expect_type(test_result, "list")
    expect_gte(length(test_result), 2000)
    expect_contains(
      names(test_result),
      c(
        "googleapis.com:adsense",
        "slack.com",
        "apis.guru"
      )
    )
  })
})
