# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

httptest2::with_mock_dir("api/path/apis/get_service_api", {
  test_that("get_service_api() returns a spec", {
    provider <- "googleapis.com"
    service <- "adsense"
    version <- "v1.4"
    test_result <- get_service_api(provider, service, version)
    expect_type(test_result, "list")
    expect_named(
      test_result,
      c(
        "openapi",
        "servers",
        "info",
        "externalDocs",
        "tags",
        "paths",
        "components"
      )
    )
    expect_gte(length(test_result$paths), 30)
  })
})
