# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

httptest2::with_mock_dir("api/path/apis/get_providers", {
  test_that("get_providers() returns a character vector of providers", {
    expect_no_error({
      test_result <- get_providers()
    })
    expect_type(test_result, "character")
    expect_gte(length(test_result), 500)
    expect_contains(
      test_result,
      c(
        "google.com",
        "microsoft.com",
        "amazonaws.com",
        "twilio.com",
        "stripe.com"
      )
    )
  })
})
