# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

httptest2::with_mock_dir("api/path/apis/get_services", {
  test_that("get_services() returns character vector of services for a given provider", {
    expect_no_error({
      test_result <- get_services("googleapis.com")
    })
    expect_type(test_result, "character")
    expect_gte(length(test_result), 200)
    expect_contains(
      test_result,
      c(
        "adsense",
        "analytics",
        "calendar",
        "docs",
        "sheets",
        "youtube"
      )
    )
  })
})
