# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

httptest2::with_mock_dir("api/path/apis/get_provider", {
  test_that("get_provider() returns a list of APIs", {
    provider <- "googleapis.com"
    sample_apis <- c(
      "adsense",
      "analytics",
      "calendar",
      "docs",
      "sheets",
      "youtube"
    )
    expect_no_error({
      test_result <- get_provider(provider)
    })
    expect_type(test_result, "list")
    expect_length(test_result, 1)
    expect_named(test_result, "apis")
    expect_type(test_result$apis, "list")
    expect_gte(length(test_result$apis), 200)
    expect_contains(
      names(test_result$apis),
      paste(provider, sample_apis, sep = ":")
    )
    expect_type(test_result$apis$`googleapis.com:adsense`, "list")
    expect_named(
      test_result$apis$`googleapis.com:adsense`,
      c(
        "added",
        "info",
        "externalDocs",
        "updated",
        "swaggerUrl",
        "swaggerYamlUrl",
        "openapiVer",
        "link"
      )
    )
  })
})
