# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' List all APIs
#'
#' List all APIs in the [apis.guru](https://apis.guru) directory. Returns links
#' to the OpenAPI definitions for each API in the directory. If API exist in
#' multiple versions `preferred` one is explicitly marked. Some basic info from
#' the OpenAPI definition is cached inside each object. This allows you to
#' generate some simple views without needing to fetch the OpenAPI definition
#' for each API.
#'
#' @inheritParams .shared-params
#'
#' @returns `list_apis()`: The API response.
#' @export
list_apis <- function(max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_list_apis()
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname list_apis
#' @returns `req_list_apis()`: (`httr2_request`) A [httr2::request()] object.
#' @export
req_list_apis <- function() {
  guru_req_prepare(
    path = "/list.json",
    method = "get",
    tidy_policy = tidy_policy_list_apis()
  )
}

#' @rdname list_apis
#' @returns `tidy_policy_list_apis()`: (`nectar_tidy_policy`) A list like the
#'   ones returned by [nectar::tidy_policy_prepare()].
#' @export
tidy_policy_list_apis <- function() {
  # TODO: create a tibblify spec and use nectar::tidy_policy_json_tibblify().
  # tibblify can't guess the tspec, unfortunately.
  nectar::tidy_policy_json(simplifyVector = TRUE)
}
