# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Retrieve one version of a particular API with a serviceName.
#'
#' Returns the API entry for one specific version of an API where there is a
#' serviceName.
#'
#' @param provider (length-1 `character`)
#' @param service (length-1 `character`)
#' @param version (length-1 `character`)
#' @inheritParams .shared-params
#'
#' @returns `get_service_api()`: The API response.
#' @export
get_service_api <- function(
  provider,
  service,
  version,
  max_reqs = Inf,
  max_tries_per_req = 3
) {
  req <- req_get_service_api(
    provider = provider,
    service = service,
    version = version
  )
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_service_api
#' @returns `req_get_service_api()`: (`httr2_request`) A [httr2::request()]
#'   object.
#' @export
req_get_service_api <- function(provider, service, version) {
  provider <- stbl::to_chr_scalar(provider)
  service <- stbl::to_chr_scalar(service)
  version <- stbl::to_chr_scalar(version)
  guru_req_prepare(
    path = c(
      "/specs/{provider}/{service}/{version}/openapi.json",
      provider = provider,
      service = service,
      version = version
    ),
    method = "get",
    tidy_policy = tidy_policy_get_service_api()
  )
}

#' @rdname get_service_api
#' @returns `tidy_policy_get_service_api()`: (`nectar_tidy_policy`) A list like
#'   the ones returned by [nectar::tidy_policy_prepare()].
#' @export
tidy_policy_get_service_api <- function() {
  nectar::tidy_policy_json()
}
