# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' List all services for a particular provider
#'
#' List all services in the [apis.guru](https://apis.guru) directory for a
#' particular provider.
#'
#' @param provider (length-1 `character`)
#' @inheritParams .shared-params
#'
#' @returns `get_services()`: The API response.
#' @export
get_services <- function(provider, max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_services(provider = provider)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_services
#' @returns `req_get_services()`: (`httr2_request`) A [httr2::request()] object.
#' @export
req_get_services <- function(provider) {
  provider <- stbl::to_chr_scalar(provider)
  guru_req_prepare(
    path = c("/{provider}/services.json", provider = provider),
    method = "get",
    tidy_policy = tidy_policy_get_services()
  )
}

#' @rdname get_services
#' @returns `tidy_policy_get_services()`: (`nectar_tidy_policy`) A list like the
#'   ones returned by [nectar::tidy_policy_prepare()].
#' @export
tidy_policy_get_services <- function() {
  nectar::tidy_policy_json(subset_path = "data", simplifyVector = TRUE)
}
