# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get basic metrics
#'
#' Some basic metrics for the entire [apis.guru](https://apis.guru) directory.
#'
#' @inheritParams .shared-params
#'
#' @returns `get_metrics()`: The API response.
#' @export
get_metrics <- function(max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_metrics()
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_metrics
#' @returns `req_get_metrics()`: (`httr2_request`) A [httr2::request()] object.
#' @export
req_get_metrics <- function() {
  guru_req_prepare(
    path = "/metrics.json",
    method = "get",
    tidy_policy = tidy_policy_get_metrics()
  )
}

#' @rdname get_metrics
#' @returns `tidy_policy_get_metrics()`: (`nectar_tidy_policy`) A list like the
#'   ones returned by [nectar::tidy_policy_prepare()].
#' @export
tidy_policy_get_metrics <- function() {
  spec <- tibblify::tspec_row(
    tibblify::tib_variant("datasets", .required = FALSE),
    tibblify::tib_int("fixedPct", .required = FALSE),
    tibblify::tib_int("fixes", .required = FALSE),
    tibblify::tib_int("invalid", .required = FALSE),
    tibblify::tib_int("issues", .required = FALSE),
    tibblify::tib_int("numAPIs"),
    tibblify::tib_int("numDrivers", .required = FALSE),
    tibblify::tib_int("numEndpoints"),
    tibblify::tib_int("numProviders", .required = FALSE),
    tibblify::tib_int("numSpecs"),
    tibblify::tib_int("stars", .required = FALSE),
    tibblify::tib_row(
      "thisWeek",
      .required = FALSE,
      tibblify::tib_int("added", .required = FALSE),
      tibblify::tib_int("updated", .required = FALSE),
    ),
    tibblify::tib_int("unofficial", .required = FALSE),
    tibblify::tib_int("unreachable", .required = FALSE),
  )
  nectar::tidy_policy_json_tibblify(spec = spec)
}
