# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' List all providers
#'
#' List all the providers in the [apis.guru](https://apis.guru) directory.
#'
#' @inheritParams .shared-params
#'
#' @returns `get_providers()`: The API response.
#' @export
get_providers <- function(max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_providers()
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_providers
#' @returns `req_get_providers()`: (`httr2_request`) A [httr2::request()]
#'   object.
#' @export
req_get_providers <- function() {
  guru_req_prepare(
    path = "/providers.json",
    method = "get",
    tidy_policy = tidy_policy_get_providers()
  )
}

#' @rdname get_providers
#' @returns `tidy_policy_get_providers()`: (`nectar_tidy_policy`) A list like
#'   the ones returned by [nectar::tidy_policy_prepare()].
#' @export
tidy_policy_get_providers <- function() {
  nectar::tidy_policy_json(subset_path = "data", simplifyVector = TRUE)
}
